name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'Release*'

permissions:
  contents: write

jobs:
  Build:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      - name: Get Tag
        id: var
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build APK
        run: bash ./gradlew assembleRelease

      # https://github.com/marketplace/actions/sign-android-release
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # https://github.com/marketplace/actions/auto-changelog
      # require commit format are "type(category): description [flag]"
      - name: Make Changelog
        uses: ardalanamini/auto-changelog@v3
        id: changelog
        with:
          github-token: ${{ github.token }}
          commit-types: |
            breaking: Breaking Changes
            feat: New Features
            fix: Bug Fixes
            revert: Reverts
            perf: Performance Improvements
            refactor: Refactors
            deps: Dependencies
            docs: Documentation Changes
            style: Code Style Changes
            build: Build System
            ci: Continuous Integration
            test: Tests
            chore: Chores
            other: Other Changes
          default-commit-type: Other Changes
          mention-authors: false
          mention-new-contributors: true
          include-compare: false
          semver: false

      # https://github.com/marketplace/actions/gh-release
      - name: Release APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ github.token }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
          files: ${{steps.sign_apk.outputs.signedReleaseFile}}
